#!/usr/bin/env ruby

=begin
Copyright (C) 2018 Mark D. Blackwell.
   All rights reserved.
   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
=end

=begin
Email comments, for Qplaylist Remember Songs Comments Process
=end

require_relative '../etc/methods'

module ::QplaylistRememberCommentsProcess
  module CommandLine
    extend Methods
#   extend Methods::ModuleMethods
#   include Methods::ModuleMethods

# Don't greet.

# TODO: Consider doing 'bundle install'.

# Navigate to run Windows batch file:
    ::Dir.chdir directory_etc

# Windows Command Line Interpreter:
    com_spec = ::File.realpath ENV['ComSpec']

# Command Line Interpreter options:
#   /D     - Disable execution of AutoRun commands
#   /E:off - Disable command extensions
#   /Q     - Turns echo off
#   /C     - Carries out the command specified by string and then terminates (must be last)
    options = %w[/D /E:off /Q /C]

    filename_mail = 'mail.bat'

# Run Windows batch file:
    command_run [com_spec] + options + [filename_mail]
  end
end
